import express from 'express';
import crypto from 'crypto';
import path from 'path';
import { clearMemberCookie,hashPassword,makeMemberCookie,normalizeEmail,opaqueToken,parseCookies,sha256,validEmail,validPassword,verifyPassword } from './member-auth.js';
import { settleMemberOrder } from './member-db.js';
import { createPhase7MemberRouter } from './member-phase7.js';
const PRICE=30000,DAYS=30,SESSION_MS=30*86400000,GENERIC='Jika email dapat digunakan, petunjuk verifikasi telah dikirim.';
const safe=fn=>async(req,res,next)=>{try{await fn(req,res,next)}catch(e){next(e)}};
const text=(v,max)=>typeof v==='string'&&Buffer.byteLength(v)<=max?v:'';
const redirectAllowed=value=>{try{const u=new URL(value);return u.protocol==='https:'&&/(^|\.)midtrans\.com$/.test(u.hostname)}catch{return false}};
const providerTime=value=>{if(typeof value!=='string'||!/^\d{4}-\d\d-\d\d \d\d:\d\d:\d\d [+-]\d{4}$/.test(value))return null;const m=value.match(/^(\d{4})-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d) ([+-])(\d\d)(\d\d)$/),offset=(Number(m[8])*60+Number(m[9]))*(m[7]==='+'?1:-1),date=new Date(Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5]-offset,+m[6]));return Number.isNaN(date.valueOf())||Math.abs(Date.now()-date.valueOf())>366*86400000?null:date};
export const memberNotification=async({store,serverKey,notification,resolveProviderStatus})=>{
 if(!serverKey)return {status:503,body:{message:'Payment verification unavailable'}};
 const expected=crypto.createHash('sha512').update(`${notification.order_id||''}${notification.status_code||''}${notification.gross_amount||''}${serverKey||''}`).digest();
 let supplied;try{supplied=Buffer.from(String(notification.signature_key||''),'hex')}catch{return {status:403,body:{message:'Invalid signature'}}}
 if(supplied.length!==expected.length||!crypto.timingSafeEqual(supplied,expected))return {status:403,body:{message:'Invalid signature'}};
 if(!String(notification.order_id||'').startsWith('MEMBER-'))return null;
 if(typeof resolveProviderStatus!=='function')return {status:503,body:{message:'Payment verification unavailable'}};
 let verified;try{verified=await resolveProviderStatus(notification.order_id)}catch{return {status:503,body:{message:'Payment verification unavailable'}}}
 if(!verified||verified.order_id!==notification.order_id)return {status:400,body:{message:'Payment mismatch'}};
 const state=String(verified.transaction_status||'');
 if(['pending','expire','cancel','deny'].includes(state)){await store.setOrderState(verified.order_id,{expire:'expired',cancel:'cancelled',deny:'denied'}[state]||state);return {status:200,body:{status:'updated'}}}
 const paidAt=providerTime(verified.settlement_time);
 if(state!=='settlement'||verified.payment_type!=='qris'||String(verified.status_code)!=='200'||!paidAt)return {status:200,body:{status:'ignored'}};
 const result=await settleMemberOrder(store,{orderId:verified.order_id,amount:Number(verified.gross_amount),transactionId:verified.transaction_id,paymentType:verified.payment_type,paidAt});
 return {status:['mismatch','transaction'].includes(result.reason)?400:200,body:result};
};
export const createMemberRouter=({store,sendMail=async()=>{},createPayment,checkoutEnabled=false,production=false,privateDir,artworkDir=path.join(privateDir,'artworks'),allowedOrigins=[]})=>{
 const r=express.Router();r.use((req,res,next)=>{res.set('Cache-Control','private, no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)&&(!req.headers.origin||!allowedOrigins.includes(req.headers.origin)))return res.status(403).json({message:'Origin tidak diizinkan'});next()});
 const issue=async(member,purpose,minutes)=>{const token=opaqueToken();await store.createToken({memberId:member.id,purpose,hash:sha256(token),expiresAt:new Date(Date.now()+minutes*60000)});await sendMail({to:member.email,purpose,token})};
 const auth=safe(async(req,res,next)=>{const token=parseCookies(req.headers.cookie).nala_member_session;const m=token&&await store.sessionMember(sha256(token));if(!m)return res.status(401).json({message:'Silakan masuk'});req.member=m;req.memberToken=token;next()});
 const limited=(name,limit=8)=>safe(async(req,res,next)=>{const identity=normalizeEmail(req.body?.email);const [ip,id]=await Promise.all([store.rateLimit(sha256(`${name}:ip:${req.ip}`),limit*3,900),identity?store.rateLimit(sha256(`${name}:id:${identity}`),limit,900):true]);if(!ip||!id)return res.status(429).json({message:'Terlalu banyak percobaan. Coba lagi nanti.'});next()});
 r.post('/register',limited('register',5),safe(async(req,res)=>{const email=normalizeEmail(req.body?.email),name=text(req.body?.name,100).trim(),password=text(req.body?.password,200);if(!validEmail(email)||name.length<2||!validPassword(password))return res.status(400).json({message:'Nama, email, atau password tidak valid. Password minimal 10 karakter.'});let member=await store.findMemberByEmail(email);if(!member){member=await store.createMember({email,name,passwordHash:await hashPassword(password)});if(!member)member=await store.findMemberByEmail(email)}if(member&&!member.email_verified_at)try{await issue(member,'verify',60)}catch{}res.status(202).json({message:GENERIC})}));
 r.post('/resend-verification',limited('resend',3),safe(async(req,res)=>{const member=await store.findMemberByEmail(normalizeEmail(req.body?.email));if(member&&!member.email_verified_at)try{await issue(member,'verify',60)}catch{}res.status(202).json({message:GENERIC})}));
 r.post('/verify',limited('verify'),safe(async(req,res)=>{const token=text(req.body?.token,300);const row=token&&await store.consumeVerifyToken({hash:sha256(token)});if(!row)return res.status(400).json({message:'Tautan verifikasi tidak valid atau kedaluwarsa.'});res.json({message:'Email berhasil diverifikasi.'})}));
 r.post('/login',limited('login',10),safe(async(req,res)=>{const password=text(req.body?.password,200),member=await store.findMemberByEmail(normalizeEmail(req.body?.email));if(!member||member.suspended_at||!password||!member.email_verified_at||!await verifyPassword(password,member.password_hash))return res.status(401).json({message:'Email atau password salah, atau email belum diverifikasi.'});const token=opaqueToken();await store.createSession({memberId:member.id,hash:sha256(token),expiresAt:new Date(Date.now()+SESSION_MS)});res.set('Set-Cookie',makeMemberCookie(token,production)).json({member:{id:member.id,email:member.email,name:member.name,membershipExpiresAt:member.membership_expires_at}})}));
 r.post('/logout',auth,safe(async(req,res)=>{await store.revokeSession(sha256(req.memberToken));res.set('Set-Cookie',clearMemberCookie(production)).json({success:true})}));
 r.post('/forgot-password',limited('forgot',5),safe(async(req,res)=>{const member=await store.findMemberByEmail(normalizeEmail(req.body?.email));if(member)try{await issue(member,'reset',30)}catch{}res.status(202).json({message:'Jika akun ditemukan, petunjuk reset telah dikirim.'})}));
 r.post('/reset-password',limited('reset'),safe(async(req,res)=>{const password=text(req.body?.password,200),token=text(req.body?.token,300);if(!validPassword(password))return res.status(400).json({message:'Password minimal 10 karakter.'});const row=token&&await store.consumeResetToken({hash:sha256(token),passwordHash:await hashPassword(password)});if(!row)return res.status(400).json({message:'Tautan reset tidak valid atau kedaluwarsa.'});res.json({message:'Password diperbarui. Silakan masuk kembali.'})}));
 r.get('/me',auth,(req,res)=>res.json({member:req.member}));r.put('/profile',auth,safe(async(req,res)=>{const name=text(req.body?.name,100).trim();if(name.length<2)return res.status(400).json({message:'Nama tidak valid'});await store.query('UPDATE member_accounts SET name=$2,updated_at=now() WHERE id=$1',[req.member.id,name]);res.json({success:true})}));
 r.put('/preferences',auth,safe(async(req,res)=>{if(typeof req.body?.renewalEmails!=='boolean')return res.status(400).json({message:'Preferensi tidak valid'});await store.query('UPDATE member_accounts SET renewal_emails_enabled=$2,updated_at=now() WHERE id=$1',[req.member.id,req.body.renewalEmails]);res.json({success:true})}));
 r.get('/sessions',auth,safe(async(req,res)=>res.json({sessions:(await store.query('SELECT id,created_at,expires_at,token_hash=$2 AS current FROM member_sessions WHERE member_id=$1 AND revoked_at IS NULL AND expires_at>now() ORDER BY created_at DESC',[req.member.id,sha256(req.memberToken)])).rows})));r.delete('/sessions/:id',auth,safe(async(req,res)=>{if(!/^\d+$/.test(req.params.id))return res.status(400).json({message:'ID tidak valid'});const out=await store.query('UPDATE member_sessions SET revoked_at=now() WHERE id=$1 AND member_id=$2 AND token_hash<>$3 AND revoked_at IS NULL RETURNING id',[req.params.id,req.member.id,sha256(req.memberToken)]);out.rowCount?res.json({success:true}):res.status(404).json({message:'Sesi tidak ditemukan'})}));
    r.post('/orders',auth,safe(async(req,res)=>{if(!checkoutEnabled||!createPayment)return res.status(503).json({message:'Pembayaran member belum tersedia.'});const plan=req.body?.planId?(await store.query("SELECT id,name,price,duration_days FROM member_plans WHERE id=$1 AND status='active'",[req.body.planId])).rows[0]:null;if(req.body?.planId&&!plan)return res.status(400).json({message:'Paket tidak tersedia'});const amount=plan?.price||PRICE,durationDays=plan?.duration_days||DAYS,id=`MEMBER-${Date.now()}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;await store.createOrder({orderId:id,memberId:req.member.id,amount,durationDays,planId:plan?.id,planName:plan?.name||'30 hari'});let payment;try{payment=await createPayment({orderId:id,amount,email:req.member.email,name:req.member.name})}catch{return res.status(502).json({message:'Penyedia pembayaran gagal. Coba lagi untuk membuat pesanan baru.'})}if(!redirectAllowed(payment?.redirectUrl))return res.status(502).json({message:'URL pembayaran tidak valid.'});await store.setOrderProvider(id,payment.redirectUrl);res.status(201).json({orderId:id,amount,redirectUrl:payment.redirectUrl})}));
 r.get('/orders',auth,safe(async(req,res)=>res.json({orders:await store.listOrders(req.member.id)})));r.get('/orders/:id',auth,safe(async(req,res)=>{if(!/^MEMBER-[A-Za-z0-9-]{5,100}$/.test(req.params.id))return res.status(400).json({message:'ID tidak valid'});const order=await store.getOrder(req.params.id,req.member.id);order?res.json({order}):res.status(404).json({message:'Pesanan tidak ditemukan'})}));
 r.get('/catalog',auth,safe(async(req,res)=>{const active=req.member.membership_expires_at&&new Date(req.member.membership_expires_at)>new Date();res.json({active,courses:await store.catalog(active,req.member.id)})}));
 r.put('/progress/:lessonId',auth,safe(async(req,res)=>{const lessonId=/^\d+$/.test(req.params.lessonId)&&req.params.lessonId,position=req.body?.position,duration=req.body?.duration,completed=req.body?.completed;if(!lessonId||!Number.isInteger(position)||!Number.isInteger(duration)||position<0||duration<0||position>86400||duration>86400||(duration&&position>duration)||typeof completed!=='boolean')return res.status(400).json({message:'Progress tidak valid'});if(!req.member.membership_expires_at||new Date(req.member.membership_expires_at)<=new Date())return res.status(403).json({message:'Keanggotaan tidak aktif'});const row=(await store.query(`INSERT INTO member_progress(member_id,lesson_id,position_seconds,duration_seconds,completed) SELECT $1,l.id,$3,$4,$5 FROM member_lessons l JOIN member_chapters ch ON ch.id=l.chapter_id JOIN member_courses c ON c.id=ch.course_id WHERE l.id=$2 AND c.status='published' AND (c.release_at IS NULL OR c.release_at<=now()) AND (l.release_at IS NULL OR l.release_at<=now()) ON CONFLICT(member_id,lesson_id) DO UPDATE SET position_seconds=EXCLUDED.position_seconds,duration_seconds=EXCLUDED.duration_seconds,completed=member_progress.completed OR EXCLUDED.completed,updated_at=now() RETURNING position_seconds AS position,duration_seconds AS duration,completed,updated_at`,[req.member.id,lessonId,position,duration,completed])).rows[0];row?res.json({progress:row}):res.status(404).json({message:'Materi tidak ditemukan'})}));
 r.get('/dashboard',auth,safe(async(req,res)=>{const rows=(await store.query(`SELECT p.lesson_id,p.position_seconds AS position,p.duration_seconds AS duration,p.completed,p.updated_at,l.title AS lesson_title,c.id AS course_id,c.title AS course_title FROM member_progress p JOIN member_lessons l ON l.id=p.lesson_id JOIN member_chapters ch ON ch.id=l.chapter_id JOIN member_courses c ON c.id=ch.course_id WHERE p.member_id=$1 AND c.status='published' AND (c.release_at IS NULL OR c.release_at<=now()) AND (l.release_at IS NULL OR l.release_at<=now()) ORDER BY p.updated_at DESC LIMIT 12`,[req.member.id])).rows;res.json({continueLearning:rows.filter(x=>!x.completed).slice(0,6),recentActivity:rows})}));
 r.put('/favourites/:courseId',auth,safe(async(req,res)=>{if(!/^\d+$/.test(req.params.courseId)||typeof req.body?.favourite!=='boolean')return res.status(400).json({message:'Favorit tidak valid'});if(req.body.favourite){const out=await store.query("INSERT INTO member_favourites(member_id,course_id) SELECT $1,id FROM member_courses WHERE id=$2 AND status='published' AND (release_at IS NULL OR release_at<=now()) ON CONFLICT DO NOTHING",[req.member.id,req.params.courseId]);if(!out.rowCount&&!await store.query("SELECT 1 FROM member_favourites f JOIN member_courses c ON c.id=f.course_id WHERE f.member_id=$1 AND f.course_id=$2 AND c.status='published' AND (c.release_at IS NULL OR c.release_at<=now())",[req.member.id,req.params.courseId]).then(x=>x.rowCount))return res.status(404).json({message:'Kursus tidak ditemukan'})}else await store.query('DELETE FROM member_favourites WHERE member_id=$1 AND course_id=$2',[req.member.id,req.params.courseId]);res.json({success:true})}));
 r.get('/worksheets/:id',auth,safe(async(req,res,next)=>{if(!/^\d+$/.test(req.params.id))return res.status(400).json({message:'ID tidak valid'});if(!req.member.membership_expires_at||new Date(req.member.membership_expires_at)<=new Date())return res.status(403).json({message:'Keanggotaan tidak aktif'});const row=(await store.query("SELECT w.* FROM member_worksheets w JOIN member_lessons l ON l.id=w.lesson_id JOIN member_chapters ch ON ch.id=l.chapter_id JOIN member_courses c ON c.id=ch.course_id WHERE w.id=$1 AND c.status='published' AND (c.release_at IS NULL OR c.release_at<=now()) AND (l.release_at IS NULL OR l.release_at<=now())",[req.params.id])).rows[0];if(!row)return res.status(404).json({message:'Worksheet tidak ditemukan'});if(!/^[0-9a-f-]{36}\.pdf$/i.test(row.storage_name))return res.status(500).json({message:'Worksheet tidak tersedia'});const file=path.resolve(privateDir,row.storage_name);if(path.dirname(file)!==path.resolve(privateDir))return res.status(500).json({message:'Worksheet tidak tersedia'});res.type('application/pdf').download(file,row.original_name,e=>e&&!res.headersSent?res.status(e.code==='ENOENT'?404:500).json({message:'Worksheet tidak tersedia'}):e&&next(e))}));r.use('/program',createPhase7MemberRouter({pool:store.pool,auth,artworkDir}));r.use((error,req,res,next)=>{if(res.headersSent)return next(error);res.status(error.status||(error.type==='entity.too.large'?413:500)).json({message:error.status&&error.status<500?error.message:error.type==='entity.too.large'?'Permintaan terlalu besar':'Permintaan gagal'})});return r;
};
export const validYoutubeId=v=>/^[A-Za-z0-9_-]{11}$/.test(String(v||''));
