import express from 'express';
import crypto from 'crypto';
import path from 'path';
import { clearMemberCookie,hashPassword,makeMemberCookie,normalizeEmail,opaqueToken,parseCookies,sha256,validEmail,validPassword,verifyPassword } from './member-auth.js';
import { settleMemberOrder } from './member-db.js';
import { createPhase7MemberRouter } from './member-phase7.js';
const PRICE=30000,DAYS=30,SESSION_MS=30*86400000,GENERIC='Jika email dapat digunakan, petunjuk verifikasi telah dikirim.';
const safe=fn=>async(req,res,next)=>{try{await fn(req,res,next)}catch(e){next(e)}};
const text=(v,max)=>typeof v==='string'&&Buffer.byteLength(v)<=max?v:'';
const redirectAllowed=value=>{try{const u=new URL(value);return u.protocol==='https:'&&/(^|\.)midtrans\.com$/.test(u.hostname)}catch{return false}};
const snapToken=value=>{try{const u=new URL(value),match=u.pathname.match(/^\/snap\/v\d+\/(?:redirection|vtweb)\/([0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})\/?$/i);return u.protocol==='https:'&&['app.midtrans.com','app.sandbox.midtrans.com'].includes(u.hostname)&&!u.username&&!u.password&&!u.port&&!u.search&&!u.hash?match?.[1]||null:null}catch{return null}};
const providerTime=value=>{if(typeof value!=='string'||!/^\d{4}-\d\d-\d\d \d\d:\d\d:\d\d [+-]\d{4}$/.test(value))return null;const m=value.match(/^(\d{4})-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d) ([+-])(\d\d)(\d\d)$/),offset=(Number(m[8])*60+Number(m[9]))*(m[7]==='+'?1:-1),date=new Date(Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5]-offset,+m[6]));return Number.isNaN(date.valueOf())||Math.abs(Date.now()-date.valueOf())>366*86400000?null:date};
const providerTimestamp=date=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(date).replace('T',' ')+' +0700';
export const memberPaymentParameters=({orderId,amount,email,name,createdAt=new Date()})=>({transaction_details:{order_id:orderId,gross_amount:amount},item_details:[{id:'membership',price:amount,quantity:1,name:'Membership Nala'}],customer_details:{email,first_name:name},enabled_payments:['qris','other_qris'],expiry:{start_time:providerTimestamp(createdAt),duration:30,unit:'minute'},page_expiry:{duration:30,unit:'minute'}});
export const memberNotification=async({store,serverKey,notification,resolveProviderStatus})=>{
 if(!serverKey)return {status:503,body:{message:'Payment verification unavailable'}};
 const expected=crypto.createHash('sha512').update(`${notification.order_id||''}${notification.status_code||''}${notification.gross_amount||''}${serverKey||''}`).digest();
 let supplied;try{supplied=Buffer.from(String(notification.signature_key||''),'hex')}catch{return {status:403,body:{message:'Invalid signature'}}}
 if(supplied.length!==expected.length||!crypto.timingSafeEqual(supplied,expected))return {status:403,body:{message:'Invalid signature'}};
 if(!String(notification.order_id||'').startsWith('MEMBER-'))return null;
 if(typeof resolveProviderStatus!=='function')return {status:503,body:{message:'Payment verification unavailable'}};
 let verified;try{verified=await resolveProviderStatus(notification.order_id)}catch{return {status:503,body:{message:'Payment verification unavailable'}}}
 if(!verified||verified.order_id!==notification.order_id)return {status:400,body:{message:'Payment mismatch'}};
 const state=String(verified.transaction_status||'');
 if(['pending','expire','cancel','deny'].includes(state)){await store.setOrderState(verified.order_id,{expire:'expired',cancel:'cancelled',deny:'denied'}[state]||state);return {status:200,body:{status:'updated'}}}
 const paidAt=providerTime(verified.settlement_time);
 if(state!=='settlement'||verified.payment_type!=='qris'||String(verified.status_code)!=='200'||!paidAt)return {status:200,body:{status:'ignored'}};
 const result=await settleMemberOrder(store,{orderId:verified.order_id,amount:Number(verified.gross_amount),transactionId:verified.transaction_id,paymentType:verified.payment_type,paidAt});
 return {status:['mismatch','transaction'].includes(result.reason)?400:200,body:result};
};
export const createMemberRouter=({store,sendMail=async()=>{},createPayment,reconcileOrder,cancelPayment,checkoutEnabled=false,clientKey='',snapUrl='',production=false,privateDir,artworkDir=path.join(privateDir,'artworks'),allowedOrigins=[],now=()=>new Date()})=>{
 const r=express.Router();r.use((req,res,next)=>{res.set('Cache-Control','private, no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)&&(!req.headers.origin||!allowedOrigins.includes(req.headers.origin)))return res.status(403).json({message:'Origin tidak diizinkan'});next()});
 const issue=async(member,purpose,minutes)=>{const token=opaqueToken();await store.createToken({memberId:member.id,purpose,hash:sha256(token),expiresAt:new Date(Date.now()+minutes*60000)});await sendMail({to:member.email,purpose,token})};
 const auth=safe(async(req,res,next)=>{const token=parseCookies(req.headers.cookie).nala_member_session;const m=token&&await store.sessionMember(sha256(token));if(!m)return res.status(401).json({message:'Silakan masuk'});req.member=m;req.memberToken=token;next()});
 const limited=(name,limit=8)=>safe(async(req,res,next)=>{const identity=normalizeEmail(req.body?.email);const [ip,id]=await Promise.all([store.rateLimit(sha256(`${name}:ip:${req.ip}`),limit*3,900),identity?store.rateLimit(sha256(`${name}:id:${identity}`),limit,900):true]);if(!ip||!id)return res.status(429).json({message:'Terlalu banyak percobaan. Coba lagi nanti.'});next()});
 r.get('/checkout-capability',safe(async(_req,res)=>res.json({enabled:Boolean(checkoutEnabled&&createPayment&&clientKey&&snapUrl),...(clientKey&&snapUrl?{clientKey,snapUrl}:{}),plans:(await store.query("SELECT p.id,p.name,p.price,p.duration_days AS \"durationDays\",p.access_mode AS \"accessMode\",COALESCE(json_agg(json_build_object('id',c.id,'title',c.title,'slug',c.slug,'status',c.status) ORDER BY c.sort_order,c.title) FILTER(WHERE c.id IS NOT NULL),'[]') courses FROM member_plans p LEFT JOIN member_plan_courses pc ON pc.plan_id=p.id LEFT JOIN member_courses c ON c.id=pc.course_id WHERE p.status='active' GROUP BY p.id ORDER BY p.duration_days,p.id")).rows})));
 r.post('/register',limited('register',5),safe(async(req,res)=>{const email=normalizeEmail(req.body?.email),name=text(req.body?.name,100).trim(),password=text(req.body?.password,200);if(!validEmail(email)||name.length<2||!validPassword(password))return res.status(400).json({message:'Nama, email, atau password tidak valid. Password minimal 10 karakter.'});let member=await store.findMemberByEmail(email);if(!member){member=await store.createMember({email,name,passwordHash:await hashPassword(password)});if(!member)member=await store.findMemberByEmail(email)}if(member&&!member.email_verified_at)try{await issue(member,'verify',60)}catch{}res.status(202).json({message:GENERIC})}));
 r.post('/resend-verification',limited('resend',3),safe(async(req,res)=>{const member=await store.findMemberByEmail(normalizeEmail(req.body?.email));if(member&&!member.email_verified_at)try{await issue(member,'verify',60)}catch{}res.status(202).json({message:GENERIC})}));
 r.post('/verify',limited('verify'),safe(async(req,res)=>{const token=text(req.body?.token,300);const row=token&&await store.consumeVerifyToken({hash:sha256(token)});if(!row)return res.status(400).json({message:'Tautan verifikasi tidak valid atau kedaluwarsa.'});res.json({message:'Email berhasil diverifikasi.'})}));
 r.post('/login',limited('login',10),safe(async(req,res)=>{const password=text(req.body?.password,200),member=await store.findMemberByEmail(normalizeEmail(req.body?.email));if(!member||member.suspended_at||!password||!member.email_verified_at||!await verifyPassword(password,member.password_hash))return res.status(401).json({message:'Email atau password salah, atau email belum diverifikasi.'});const token=opaqueToken();await store.createSession({memberId:member.id,hash:sha256(token),expiresAt:new Date(Date.now()+SESSION_MS)});res.set('Set-Cookie',makeMemberCookie(token,production)).json({member:{id:member.id,email:member.email,name:member.name,membershipExpiresAt:member.membership_expires_at}})}));
 r.post('/logout',auth,safe(async(req,res)=>{await store.revokeSession(sha256(req.memberToken));res.set('Set-Cookie',clearMemberCookie(production)).json({success:true})}));
 r.post('/forgot-password',limited('forgot',5),safe(async(req,res)=>{const member=await store.findMemberByEmail(normalizeEmail(req.body?.email));if(member)try{await issue(member,'reset',30)}catch{}res.status(202).json({message:'Jika akun ditemukan, petunjuk reset telah dikirim.'})}));
 r.post('/reset-password',limited('reset'),safe(async(req,res)=>{const password=text(req.body?.password,200),token=text(req.body?.token,300);if(!validPassword(password))return res.status(400).json({message:'Password minimal 10 karakter.'});const row=token&&await store.consumeResetToken({hash:sha256(token),passwordHash:await hashPassword(password)});if(!row)return res.status(400).json({message:'Tautan reset tidak valid atau kedaluwarsa.'});res.json({message:'Password diperbarui. Silakan masuk kembali.'})}));
 r.get('/me',auth,(req,res)=>res.json({member:req.member}));r.put('/profile',auth,safe(async(req,res)=>{const name=text(req.body?.name,100).trim();if(name.length<2)return res.status(400).json({message:'Nama tidak valid'});await store.query('UPDATE member_accounts SET name=$2,updated_at=now() WHERE id=$1',[req.member.id,name]);res.json({success:true})}));
 r.put('/preferences',auth,safe(async(req,res)=>{if(typeof req.body?.renewalEmails!=='boolean')return res.status(400).json({message:'Preferensi tidak valid'});await store.query('UPDATE member_accounts SET renewal_emails_enabled=$2,updated_at=now() WHERE id=$1',[req.member.id,req.body.renewalEmails]);res.json({success:true})}));
 r.get('/sessions',auth,safe(async(req,res)=>res.json({sessions:(await store.query('SELECT id,created_at,expires_at,token_hash=$2 AS current FROM member_sessions WHERE member_id=$1 AND revoked_at IS NULL AND expires_at>now() ORDER BY created_at DESC',[req.member.id,sha256(req.memberToken)])).rows})));r.delete('/sessions/:id',auth,safe(async(req,res)=>{if(!/^\d+$/.test(req.params.id))return res.status(400).json({message:'ID tidak valid'});const out=await store.query('UPDATE member_sessions SET revoked_at=now() WHERE id=$1 AND member_id=$2 AND token_hash<>$3 AND revoked_at IS NULL RETURNING id',[req.params.id,req.member.id,sha256(req.memberToken)]);out.rowCount?res.json({success:true}):res.status(404).json({message:'Sesi tidak ditemukan'})}));
    r.post('/orders',auth,safe(async(req,res)=>{if(!checkoutEnabled||!createPayment||!clientKey||!snapUrl)return res.status(503).json({message:'Pembayaran member belum tersedia.'});const planId=/^[1-9]\d{0,18}$/.test(String(req.body?.planId))&&BigInt(req.body.planId)<=9223372036854775807n?String(req.body.planId):null;if(!planId)return res.status(400).json({message:'Paket tidak tersedia'});const createdAt=now(),expiresAt=new Date(createdAt.getTime()+30*60000),id=`MEMBER-${createdAt.getTime()}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`,reserve=()=>store.reserveCheckout({orderId:id,memberId:req.member.id,planId,expiresAt,create:order=>createPayment({orderId:id,amount:order.amount,email:req.member.email,name:req.member.name,createdAt})});let out=await reserve();if(out.unavailable)return res.status(400).json({message:'Paket tidak tersedia'});if(out.existing&&reconcileOrder){const pending=(await store.query("SELECT order_id FROM member_orders WHERE member_id=$1 AND status='pending' ORDER BY created_at,id LIMIT 3",[req.member.id])).rows;for(const order of pending)try{await reconcileOrder(order.order_id)}catch{}out=await reserve()}if(out.existing)return res.status(409).json({message:'Pesanan aktif belum dapat dipastikan selesai. Lanjutkan, batalkan, atau coba lagi setelah status penyedia berubah.',existingOrder:out.existing,unresolvedCount:out.unresolvedCount});if(out.error)return res.status(502).json({message:'Status pembuatan pembayaran belum dapat dipastikan. Pesanan tetap aktif; coba lanjutkan atau batalkan setelah verifikasi.',orderId:id,expiresAt});if(!out.payment?.token||!redirectAllowed(out.payment.redirectUrl))return res.status(502).json({message:'Respons penyedia pembayaran tidak valid; pesanan tetap aktif.'});res.status(201).json({orderId:id,amount:out.order.amount,token:out.payment.token,redirectUrl:out.payment.redirectUrl,expiresAt})}));
 r.post('/orders/:id/cancel',auth,safe(async(req,res)=>{if(!/^MEMBER-[A-Za-z0-9-]{5,100}$/.test(req.params.id)||req.body?.confirm!==true)return res.status(400).json({message:'Pesanan atau konfirmasi tidak valid'});const privateOrder=await store.getOrderForCancel(req.params.id,req.member.id);if(!privateOrder)return res.status(404).json({message:'Pesanan tidak ditemukan'});if(privateOrder.fulfilled_at||privateOrder.status!=='pending')return res.status(409).json({message:privateOrder.status==='paid'?'Pesanan sudah dibayar dan tidak dapat dibatalkan.':'Pesanan sudah selesai.'});const token=privateOrder.provider_token||snapToken(privateOrder.provider_redirect_url);if(!token)return res.status(409).json({message:'Sesi pembayaran belum terverifikasi; pesanan tetap aktif.'});let cancelled;try{cancelled=await cancelPayment(token)}catch(e){return res.status(e?.httpStatusCode===404?409:503).json({message:e?.httpStatusCode===404?'Sesi Snap belum terverifikasi batal; pesanan tetap aktif.':'Pembatalan penyedia gagal; pesanan tetap aktif.'})}if(!cancelled?.canceled_at)return res.status(409).json({message:'Respons pembatalan Snap belum terverifikasi; pesanan tetap aktif.'});try{await reconcileOrder(req.params.id)}catch(e){if(e?.httpStatusCode!==404)return res.status(503).json({message:'Pembatalan belum dapat diverifikasi; pesanan tetap aktif.'});await store.cancelPendingOrder(req.params.id,req.member.id)}const order=await store.getOrder(req.params.id,req.member.id);if(order.status==='paid')return res.status(409).json({message:'Pembayaran masuk saat pembatalan; pesanan tidak dibatalkan.'});if(!['cancelled','expired','denied'].includes(order.status))return res.status(409).json({message:'Sesi masih dapat dibayar; pesanan tetap aktif.'});res.json({cancelled:true,order})}));
 r.get('/orders',auth,safe(async(req,res)=>res.json({orders:await store.listOrders(req.member.id,req.query.archived==='true')})));r.get('/orders/:id',auth,safe(async(req,res)=>{if(!/^MEMBER-[A-Za-z0-9-]{5,100}$/.test(req.params.id))return res.status(400).json({message:'ID tidak valid'});let order=await store.getOrder(req.params.id,req.member.id);if(!order)return res.status(404).json({message:'Pesanan tidak ditemukan'});if(order.status==='pending'&&reconcileOrder){try{await reconcileOrder(order.order_id)}catch{}order=await store.getOrder(req.params.id,req.member.id)}res.json({order})}));
 r.get('/catalog',auth,safe(async(req,res)=>{const courses=await store.catalog(false,req.member.id);res.json({active:courses.some(c=>c.accessible),courses})}));
 r.put('/progress/:lessonId',auth,safe(async(req,res)=>{const lessonId=/^\d+$/.test(req.params.lessonId)&&req.params.lessonId,position=req.body?.position,duration=req.body?.duration,completed=req.body?.completed;if(!lessonId||!Number.isInteger(position)||!Number.isInteger(duration)||position<0||duration<0||position>86400||duration>86400||(duration&&position>duration)||typeof completed!=='boolean')return res.status(400).json({message:'Progress tidak valid'});const row=(await store.query(`INSERT INTO member_progress(member_id,lesson_id,position_seconds,duration_seconds,completed) SELECT $1,l.id,$3,$4,$5 FROM member_lessons l JOIN member_chapters ch ON ch.id=l.chapter_id JOIN member_courses c ON c.id=ch.course_id JOIN member_accounts a ON a.id=$1 WHERE l.id=$2 AND (a.membership_expires_at>now() OR EXISTS(SELECT 1 FROM member_course_grants g WHERE g.member_id=$1 AND g.course_id=c.id AND g.expires_at>now())) AND c.status='published' AND (c.release_at IS NULL OR c.release_at<=now()) AND (l.release_at IS NULL OR l.release_at<=now()) ON CONFLICT(member_id,lesson_id) DO UPDATE SET position_seconds=EXCLUDED.position_seconds,duration_seconds=EXCLUDED.duration_seconds,completed=member_progress.completed OR EXCLUDED.completed,updated_at=now() RETURNING position_seconds AS position,duration_seconds AS duration,completed,updated_at`,[req.member.id,lessonId,position,duration,completed])).rows[0];row?res.json({progress:row}):res.status(403).json({message:'Materi tidak tersedia untuk paket ini'})}));
 r.get('/dashboard',auth,safe(async(req,res)=>{const rows=(await store.query(`SELECT p.lesson_id,p.position_seconds AS position,p.duration_seconds AS duration,p.completed,p.updated_at,l.title AS lesson_title,c.id AS course_id,c.title AS course_title FROM member_progress p JOIN member_lessons l ON l.id=p.lesson_id JOIN member_chapters ch ON ch.id=l.chapter_id JOIN member_courses c ON c.id=ch.course_id JOIN member_accounts a ON a.id=p.member_id WHERE p.member_id=$1 AND (a.membership_expires_at>now() OR EXISTS(SELECT 1 FROM member_course_grants g WHERE g.member_id=$1 AND g.course_id=c.id AND g.expires_at>now())) AND c.status='published' AND (c.release_at IS NULL OR c.release_at<=now()) AND (l.release_at IS NULL OR l.release_at<=now()) ORDER BY p.updated_at DESC LIMIT 12`,[req.member.id])).rows;res.json({continueLearning:rows.filter(x=>!x.completed).slice(0,6),recentActivity:rows})}));
 r.put('/favourites/:courseId',auth,safe(async(req,res)=>{if(!/^\d+$/.test(req.params.courseId)||typeof req.body?.favourite!=='boolean')return res.status(400).json({message:'Favorit tidak valid'});if(req.body.favourite){const out=await store.query("INSERT INTO member_favourites(member_id,course_id) SELECT $1,c.id FROM member_courses c JOIN member_accounts a ON a.id=$1 WHERE c.id=$2 AND (a.membership_expires_at>now() OR EXISTS(SELECT 1 FROM member_course_grants g WHERE g.member_id=$1 AND g.course_id=c.id AND g.expires_at>now())) AND c.status='published' AND (c.release_at IS NULL OR c.release_at<=now()) ON CONFLICT DO NOTHING",[req.member.id,req.params.courseId]);if(!out.rowCount)return res.status(403).json({message:'Kursus tidak tersedia untuk paket ini'})}else await store.query('DELETE FROM member_favourites WHERE member_id=$1 AND course_id=$2',[req.member.id,req.params.courseId]);res.json({success:true})}));
 r.get('/worksheets/:id',auth,safe(async(req,res,next)=>{if(!/^\d+$/.test(req.params.id))return res.status(400).json({message:'ID tidak valid'});const row=(await store.query("SELECT w.* FROM member_worksheets w JOIN member_lessons l ON l.id=w.lesson_id JOIN member_chapters ch ON ch.id=l.chapter_id JOIN member_courses c ON c.id=ch.course_id JOIN member_accounts a ON a.id=$2 WHERE w.id=$1 AND (a.membership_expires_at>now() OR EXISTS(SELECT 1 FROM member_course_grants g WHERE g.member_id=$2 AND g.course_id=c.id AND g.expires_at>now())) AND c.status='published' AND (c.release_at IS NULL OR c.release_at<=now()) AND (l.release_at IS NULL OR l.release_at<=now())",[req.params.id,req.member.id])).rows[0];if(!row)return res.status(403).json({message:'Worksheet tidak tersedia untuk paket ini'});if(!/^[0-9a-f-]{36}\.pdf$/i.test(row.storage_name))return res.status(500).json({message:'Worksheet tidak tersedia'});const file=path.resolve(privateDir,row.storage_name);if(path.dirname(file)!==path.resolve(privateDir))return res.status(500).json({message:'Worksheet tidak tersedia'});res.type('application/pdf').download(file,row.original_name,e=>e&&!res.headersSent?res.status(e.code==='ENOENT'?404:500).json({message:'Worksheet tidak tersedia'}):e&&next(e))}));r.use('/program',createPhase7MemberRouter({pool:store.pool,auth,artworkDir}));r.use((error,req,res,next)=>{if(res.headersSent)return next(error);res.status(error.status||(error.type==='entity.too.large'?413:500)).json({message:error.status&&error.status<500?error.message:error.type==='entity.too.large'?'Permintaan terlalu besar':'Permintaan gagal'})});return r;
};
export const validYoutubeId=v=>/^[A-Za-z0-9_-]{11}$/.test(String(v||''));
