export const createMemberStore = (pool) => ({
  pool,
  query: (text, values) => pool.query(text, values),
  transaction: async (fn) => { const client=await pool.connect(); try { await client.query('BEGIN'); const out=await fn(client); await client.query('COMMIT'); return out; } catch(e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } },
  findMemberByEmail: async email => (await pool.query('SELECT * FROM member_accounts WHERE lower(email)=lower($1)',[email])).rows[0],
  findMemberById: async id => (await pool.query('SELECT id,email,name,email_verified_at,membership_expires_at FROM member_accounts WHERE id=$1',[id])).rows[0],
  createMember: async ({email,name,passwordHash}) => (await pool.query('INSERT INTO member_accounts(email,name,password_hash) VALUES($1,$2,$3) ON CONFLICT ((lower(email))) DO NOTHING RETURNING id,email,name',[email,name,passwordHash])).rows[0],
  createToken: async ({memberId,purpose,hash,expiresAt}) => pool.query('WITH x AS (UPDATE member_tokens SET used_at=now() WHERE member_id=$1 AND purpose=$2 AND used_at IS NULL) INSERT INTO member_tokens(member_id,purpose,token_hash,expires_at) VALUES($1,$2,$3,$4)',[memberId,purpose,hash,expiresAt]),
  consumeVerifyToken: ({hash}) => pool.query("WITH t AS (UPDATE member_tokens SET used_at=now() WHERE id=(SELECT id FROM member_tokens WHERE token_hash=$1 AND purpose='verify' AND used_at IS NULL AND expires_at>now() FOR UPDATE) RETURNING member_id) UPDATE member_accounts a SET email_verified_at=COALESCE(a.email_verified_at,now()),updated_at=now() FROM t WHERE a.id=t.member_id RETURNING a.id",[hash]).then(x=>x.rows[0]),
  consumeResetToken: ({hash,passwordHash}) => pool.query("WITH t AS (UPDATE member_tokens SET used_at=now() WHERE id=(SELECT id FROM member_tokens WHERE token_hash=$1 AND purpose='reset' AND used_at IS NULL AND expires_at>now() FOR UPDATE) RETURNING member_id), a AS (UPDATE member_accounts SET password_hash=$2,updated_at=now() WHERE id=(SELECT member_id FROM t) RETURNING id), revoked AS (UPDATE member_sessions SET revoked_at=now() WHERE member_id=(SELECT id FROM a) AND revoked_at IS NULL) SELECT id FROM a",[hash,passwordHash]).then(x=>x.rowCount?{ok:true}:null),
  createSession: ({memberId,hash,expiresAt}) => pool.query('INSERT INTO member_sessions(member_id,token_hash,expires_at) VALUES($1,$2,$3)',[memberId,hash,expiresAt]),
  sessionMember: async hash => (await pool.query('SELECT a.id,a.email,a.name,a.email_verified_at,a.membership_expires_at,a.renewal_emails_enabled FROM member_sessions s JOIN member_accounts a ON a.id=s.member_id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() AND a.suspended_at IS NULL',[hash])).rows[0],
  revokeSession: hash => pool.query('UPDATE member_sessions SET revoked_at=now() WHERE token_hash=$1',[hash]),
  rateLimit: async (keyHash,limit,seconds) => (await pool.query("INSERT INTO member_rate_limits(key_hash,attempts,window_started_at) VALUES($1,1,now()) ON CONFLICT(key_hash) DO UPDATE SET attempts=CASE WHEN member_rate_limits.window_started_at < now()-($3||' seconds')::interval THEN 1 ELSE member_rate_limits.attempts+1 END,window_started_at=CASE WHEN member_rate_limits.window_started_at < now()-($3||' seconds')::interval THEN now() ELSE member_rate_limits.window_started_at END RETURNING attempts <= $2 AS allowed",[keyHash,limit,seconds])).rows[0].allowed,
  createOrder: async x => (await pool.query('INSERT INTO member_orders(order_id,member_id,amount,duration_days,plan_id,plan_name) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[x.orderId,x.memberId,x.amount,x.durationDays,x.planId||null,x.planName||'30 hari'])).rows[0],
  setOrderProvider: async (id,url) => (await pool.query('UPDATE member_orders SET provider_redirect_url=$2,updated_at=now() WHERE order_id=$1 RETURNING *',[id,url])).rows[0],
  setOrderState: (id,status) => pool.query("UPDATE member_orders SET status=$2,updated_at=now() WHERE order_id=$1 AND fulfilled_at IS NULL AND status<>'paid'",[id,status]),
  getOrder: async (id,memberId) => (await pool.query('SELECT order_id,amount,duration_days,status,provider_redirect_url,paid_at,created_at,archived_at FROM member_orders WHERE order_id=$1 AND member_id=$2',[id,memberId])).rows[0],
  listOrders: async (memberId,archived=false) => (await pool.query(`SELECT order_id,amount,duration_days,status,provider_redirect_url,paid_at,created_at,archived_at FROM member_orders WHERE member_id=$1 AND archived_at IS ${archived?'NOT ':''}NULL ORDER BY created_at DESC`,[memberId])).rows,
  catalog: async (active,memberId) => (await pool.query(`SELECT c.id,c.slug,c.title,c.description,c.category,c.image_url,c.sort_order,EXISTS(SELECT 1 FROM member_favourites f WHERE f.member_id=$1 AND f.course_id=c.id) favourite,COALESCE(json_agg(json_build_object('id',ch.id,'title',ch.title,'sortOrder',ch.sort_order,'lessons',(SELECT COALESCE(json_agg(json_build_object('id',l.id,'title',l.title,'description',l.description,'sortOrder',l.sort_order,'isPreview',l.is_preview,'youtubeVideoId',CASE WHEN $2 OR l.is_preview THEN l.youtube_video_id END,'progress',(SELECT row_to_json(p) FROM (SELECT position_seconds AS position,duration_seconds AS duration,completed FROM member_progress WHERE member_id=$1 AND lesson_id=l.id) p),'worksheets',(SELECT COALESCE(json_agg(json_build_object('id',w.id,'title',w.title)),'[]') FROM member_worksheets w WHERE w.lesson_id=l.id)) ORDER BY l.sort_order),'[]') FROM member_lessons l WHERE l.chapter_id=ch.id AND (l.release_at IS NULL OR l.release_at<=now()))) ORDER BY ch.sort_order) FILTER (WHERE ch.id IS NOT NULL),'[]') chapters FROM member_courses c LEFT JOIN member_chapters ch ON ch.course_id=c.id WHERE c.status='published' AND (c.release_at IS NULL OR c.release_at<=now()) GROUP BY c.id ORDER BY c.sort_order,c.title`,[memberId,active])).rows
});

export const settleMemberOrder=(store,{orderId,amount,transactionId,paymentType,paidAt=new Date()})=>store.transaction(async client=>{
  if(!transactionId||typeof transactionId!=='string'||transactionId.length>200)return {applied:false,reason:'transaction'};
  const order=(await client.query('SELECT * FROM member_orders WHERE order_id=$1 FOR UPDATE',[orderId])).rows[0];
  if(!order||Number(order.amount)!==Number(amount)||paymentType!=='qris')return {applied:false,reason:'mismatch'};
  if(order.fulfilled_at)return {applied:false,reason:'duplicate'};
  const used=await client.query('SELECT order_id FROM member_orders WHERE provider_transaction_id=$1 AND order_id<>$2 FOR UPDATE',[transactionId,orderId]);
  if(used.rowCount)return {applied:false,reason:'transaction'};
  const account=(await client.query('SELECT membership_expires_at FROM member_accounts WHERE id=$1 FOR UPDATE',[order.member_id])).rows[0];
  const updated=(await client.query("UPDATE member_accounts SET membership_expires_at=GREATEST(COALESCE(membership_expires_at,$2),$2)+($3||' days')::interval,updated_at=now() WHERE id=$1 RETURNING membership_expires_at",[order.member_id,paidAt,order.duration_days])).rows[0];
  await client.query("UPDATE member_orders SET status='paid',provider_transaction_id=$2,payment_type=$3,paid_at=$4,fulfilled_at=now(),updated_at=now() WHERE id=$1",[order.id,transactionId,paymentType,paidAt]);
  try{await client.query("INSERT INTO member_access_ledger(member_id,source_type,source_id,days_delta,previous_expires_at,resulting_expires_at,actor) VALUES($1,'payment',$2,$3,$4,$5,'provider') ON CONFLICT DO NOTHING",[order.member_id,order.order_id,order.duration_days,account?.membership_expires_at||null,updated.membership_expires_at])}catch(e){if(e.code!=='42P01')throw e}
  return {applied:true,expiresAt:updated.membership_expires_at};
});
