export const percentageVoucherAmount=(price,percent)=>Math.floor(price*(100-percent)/100);
export const createMemberStore = (pool) => ({
  pool,
  query: (text, values) => pool.query(text, values),
  transaction: async (fn) => { const client=await pool.connect(); try { await client.query('BEGIN'); const out=await fn(client); await client.query('COMMIT'); return out; } catch(e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } },
  findMemberByEmail: async email => (await pool.query('SELECT * FROM member_accounts WHERE lower(email)=lower($1)',[email])).rows[0],
  findMemberById: async id => (await pool.query('SELECT id,email,name,email_verified_at,membership_expires_at FROM member_accounts WHERE id=$1',[id])).rows[0],
  createMember: async ({email,name,passwordHash}) => (await pool.query('INSERT INTO member_accounts(email,name,password_hash) VALUES($1,$2,$3) ON CONFLICT ((lower(email))) DO NOTHING RETURNING id,email,name',[email,name,passwordHash])).rows[0],
  createToken: async ({memberId,purpose,hash,expiresAt}) => pool.query('WITH x AS (UPDATE member_tokens SET used_at=now() WHERE member_id=$1 AND purpose=$2 AND used_at IS NULL) INSERT INTO member_tokens(member_id,purpose,token_hash,expires_at) VALUES($1,$2,$3,$4)',[memberId,purpose,hash,expiresAt]),
  consumeVerifyToken: ({hash}) => pool.query("WITH t AS (UPDATE member_tokens SET used_at=now() WHERE id=(SELECT id FROM member_tokens WHERE token_hash=$1 AND purpose='verify' AND used_at IS NULL AND expires_at>now() FOR UPDATE) RETURNING member_id) UPDATE member_accounts a SET email_verified_at=COALESCE(a.email_verified_at,now()),updated_at=now() FROM t WHERE a.id=t.member_id RETURNING a.id",[hash]).then(x=>x.rows[0]),
  consumeResetToken: ({hash,passwordHash}) => pool.query("WITH t AS (UPDATE member_tokens SET used_at=now() WHERE id=(SELECT id FROM member_tokens WHERE token_hash=$1 AND purpose='reset' AND used_at IS NULL AND expires_at>now() FOR UPDATE) RETURNING member_id), a AS (UPDATE member_accounts SET password_hash=$2,updated_at=now() WHERE id=(SELECT member_id FROM t) RETURNING id), revoked AS (UPDATE member_sessions SET revoked_at=now() WHERE member_id=(SELECT id FROM a) AND revoked_at IS NULL) SELECT id FROM a",[hash,passwordHash]).then(x=>x.rowCount?{ok:true}:null),
  createSession: ({memberId,hash,expiresAt}) => pool.query('INSERT INTO member_sessions(member_id,token_hash,expires_at) VALUES($1,$2,$3)',[memberId,hash,expiresAt]),
  sessionMember: async hash => (await pool.query('SELECT a.id,a.email,a.name,a.email_verified_at,a.membership_expires_at,a.renewal_emails_enabled FROM member_sessions s JOIN member_accounts a ON a.id=s.member_id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() AND a.suspended_at IS NULL',[hash])).rows[0],
  revokeSession: hash => pool.query('UPDATE member_sessions SET revoked_at=now() WHERE token_hash=$1',[hash]),
  rateLimit: async (keyHash,limit,seconds) => (await pool.query("INSERT INTO member_rate_limits(key_hash,attempts,window_started_at) VALUES($1,1,now()) ON CONFLICT(key_hash) DO UPDATE SET attempts=CASE WHEN member_rate_limits.window_started_at < now()-($3||' seconds')::interval THEN 1 ELSE member_rate_limits.attempts+1 END,window_started_at=CASE WHEN member_rate_limits.window_started_at < now()-($3||' seconds')::interval THEN now() ELSE member_rate_limits.window_started_at END RETURNING attempts <= $2 AS allowed",[keyHash,limit,seconds])).rows[0].allowed,
  createOrder: async x => (await pool.query('INSERT INTO member_orders(order_id,member_id,amount,duration_days,plan_id,plan_name) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[x.orderId,x.memberId,x.amount,x.durationDays,x.planId||null,x.planName||'30 hari'])).rows[0],
  reserveCheckout: async x => {const client=await pool.connect();let order;try{await client.query('BEGIN');await client.query('SELECT id FROM member_accounts WHERE id=$1 FOR UPDATE',[x.memberId]);const unresolved=(await client.query("SELECT order_id,amount,duration_days,status,provider_redirect_url,checkout_expires_at,created_at FROM member_orders WHERE member_id=$1 AND status='pending' ORDER BY created_at,id",[x.memberId])).rows;if(unresolved.length){await client.query('COMMIT');return {existing:unresolved[0],unresolvedCount:unresolved.length}}const plan=(await client.query("SELECT id,name,price,duration_days,access_mode FROM member_plans WHERE id=$1 AND status='active' FOR UPDATE",[x.planId])).rows[0];if(!plan){await client.query('ROLLBACK');return {unavailable:true}}let voucher=null;if(x.voucherHash){voucher=(await client.query('SELECT * FROM member_vouchers WHERE code_hash=$1 FOR UPDATE',[x.voucherHash])).rows[0];if(!voucher||voucher.plan_id!==plan.id||!voucher.discount_percent||voucher.archived_at||!voucher.expires_at||voucher.expires_at<=x.createdAt||voucher.uses>=voucher.max_uses||(await client.query('SELECT 1 FROM member_orders WHERE voucher_id=$1 AND member_id=$2',[voucher.id,x.memberId])).rowCount){await client.query('ROLLBACK');return {invalidVoucher:true}}}const amount=voucher?percentageVoucherAmount(plan.price,voucher.discount_percent):plan.price;order=(await client.query('INSERT INTO member_orders(order_id,member_id,amount,original_amount,duration_days,plan_id,plan_name,checkout_expires_at,access_mode,voucher_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[x.orderId,x.memberId,amount,voucher?plan.price:null,plan.duration_days,plan.id,plan.name,x.expiresAt,plan.access_mode,voucher?.id||null])).rows[0];if(voucher)await client.query('UPDATE member_vouchers SET uses=uses+1 WHERE id=$1',[voucher.id]);if(order.access_mode==='selected'){const snapshot=await client.query('INSERT INTO member_order_courses(order_id,course_id) SELECT $1,course_id FROM member_plan_courses WHERE plan_id=$2 RETURNING course_id',[order.id,plan.id]);if(!snapshot.rowCount){await client.query('ROLLBACK');return {unavailable:true}}}await client.query('COMMIT')}catch(e){try{await client.query('ROLLBACK')}catch{}throw e}finally{client.release()}try{const payment=await x.create(order);if(payment?.token&&payment?.redirectUrl)await pool.query('UPDATE member_orders SET provider_token=$2,provider_redirect_url=$3,updated_at=now() WHERE order_id=$1',[x.orderId,payment.token,payment.redirectUrl]);return {order,payment}}catch(error){return {order,error}}},
  setOrderProvider: async (id,url,token) => (await pool.query('UPDATE member_orders SET provider_redirect_url=$2,provider_token=$3,updated_at=now() WHERE order_id=$1 RETURNING *',[id,url,token||null])).rows[0],
  setOrderState: (id,status) => pool.query("UPDATE member_orders SET status=$2,updated_at=now() WHERE order_id=$1 AND fulfilled_at IS NULL AND status<>'paid'",[id,status]),
  getOrder: async (id,memberId) => (await pool.query(`SELECT o.order_id,o.amount,o.duration_days,o.status,o.provider_redirect_url,o.paid_at,o.created_at,o.checkout_expires_at,o.archived_at,o.access_mode AS "accessMode",COALESCE(json_agg(json_build_object('id',c.id,'title',c.title,'status',c.status) ORDER BY c.id) FILTER(WHERE c.id IS NOT NULL),'[]') courses FROM member_orders o LEFT JOIN member_order_courses oc ON oc.order_id=o.id LEFT JOIN member_courses c ON c.id=oc.course_id WHERE o.order_id=$1 AND o.member_id=$2 GROUP BY o.id`,[id,memberId])).rows[0],
  getOrderForCancel: async (id,memberId) => (await pool.query('SELECT order_id,amount,status,provider_token,provider_redirect_url,fulfilled_at FROM member_orders WHERE order_id=$1 AND member_id=$2',[id,memberId])).rows[0],
  cancelPendingOrder: async (id,memberId) => (await pool.query("UPDATE member_orders SET status='cancelled',updated_at=now() WHERE order_id=$1 AND member_id=$2 AND status='pending' AND fulfilled_at IS NULL RETURNING *",[id,memberId])).rows[0],
  listOrders: async (memberId,archived=false) => (await pool.query(`SELECT o.order_id,o.amount,o.duration_days,o.status,o.provider_redirect_url,o.paid_at,o.created_at,o.checkout_expires_at,o.archived_at,o.access_mode AS "accessMode",COALESCE(json_agg(json_build_object('id',c.id,'title',c.title,'status',c.status) ORDER BY c.id) FILTER(WHERE c.id IS NOT NULL),'[]') courses FROM member_orders o LEFT JOIN member_order_courses oc ON oc.order_id=o.id LEFT JOIN member_courses c ON c.id=oc.course_id WHERE o.member_id=$1 AND o.archived_at IS ${archived?'NOT ':''}NULL GROUP BY o.id ORDER BY o.created_at DESC`,[memberId])).rows,
  catalog: async (_active,memberId) => (await pool.query(`SELECT c.id,c.slug,c.title,c.description,c.category,c.image_url,c.sort_order,GREATEST(a.membership_expires_at,(SELECT max(g.expires_at) FROM member_course_grants g WHERE g.member_id=$1 AND g.course_id=c.id)) AS "accessibleUntil",(COALESCE(a.membership_expires_at>now(),false) OR EXISTS(SELECT 1 FROM member_course_grants g WHERE g.member_id=$1 AND g.course_id=c.id AND g.expires_at>now())) accessible,EXISTS(SELECT 1 FROM member_favourites f WHERE f.member_id=$1 AND f.course_id=c.id) favourite,COALESCE(json_agg(json_build_object('id',ch.id,'title',ch.title,'sortOrder',ch.sort_order,'lessons',(SELECT COALESCE(json_agg(json_build_object('id',l.id,'title',l.title,'description',l.description,'sortOrder',l.sort_order,'isPreview',l.is_preview,'youtubeVideoId',CASE WHEN a.membership_expires_at>now() OR EXISTS(SELECT 1 FROM member_course_grants g WHERE g.member_id=$1 AND g.course_id=c.id AND g.expires_at>now()) OR l.is_preview THEN l.youtube_video_id END,'progress',(SELECT row_to_json(p) FROM (SELECT position_seconds AS position,duration_seconds AS duration,completed FROM member_progress WHERE member_id=$1 AND lesson_id=l.id) p),'worksheets',(SELECT COALESCE(json_agg(json_build_object('id',w.id,'title',w.title)),'[]') FROM member_worksheets w WHERE w.lesson_id=l.id)) ORDER BY l.sort_order),'[]') FROM member_lessons l WHERE l.chapter_id=ch.id AND (l.release_at IS NULL OR l.release_at<=now()))) ORDER BY ch.sort_order) FILTER (WHERE ch.id IS NOT NULL),'[]') chapters FROM member_courses c CROSS JOIN member_accounts a LEFT JOIN member_chapters ch ON ch.course_id=c.id WHERE a.id=$1 AND c.status='published' AND (c.release_at IS NULL OR c.release_at<=now()) GROUP BY c.id,a.membership_expires_at ORDER BY c.sort_order,c.title`,[memberId])).rows
});

export const settleMemberOrder=(store,{orderId,amount,transactionId,paymentType,paidAt=new Date()})=>store.transaction(async client=>{
  if(!transactionId||typeof transactionId!=='string'||transactionId.length>200)return {applied:false,reason:'transaction'};
  const order=(await client.query('SELECT * FROM member_orders WHERE order_id=$1 FOR UPDATE',[orderId])).rows[0];
  if(!order||Number(order.amount)!==Number(amount)||paymentType!=='qris')return {applied:false,reason:'mismatch'};
  if(order.fulfilled_at)return {applied:false,reason:'duplicate'};
  const used=await client.query('SELECT order_id FROM member_orders WHERE provider_transaction_id=$1 AND order_id<>$2 FOR UPDATE',[transactionId,orderId]);
  if(used.rowCount)return {applied:false,reason:'transaction'};
  const account=(await client.query('SELECT membership_expires_at FROM member_accounts WHERE id=$1 FOR UPDATE',[order.member_id])).rows[0];
  let updated=account,courseGrants=[];
  if(order.access_mode==='selected'){
    const snapshot=await client.query('SELECT course_id FROM member_order_courses WHERE order_id=$1 ORDER BY course_id FOR UPDATE',[order.id]);
    if(!snapshot.rowCount)return {applied:false,reason:'snapshot'};
    for(const {course_id} of snapshot.rows){await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1||':'||$2,0))",[order.member_id,course_id]);const prior=(await client.query('SELECT max(expires_at) expires_at FROM member_course_grants WHERE member_id=$1 AND course_id=$2',[order.member_id,course_id])).rows[0]?.expires_at;const start=prior&&prior>paidAt?prior:paidAt;courseGrants.push((await client.query("INSERT INTO member_course_grants(member_id,course_id,source_order_id,starts_at,expires_at) VALUES($1,$2,$3,$4::timestamptz,$4::timestamptz+($5||' days')::interval) RETURNING course_id AS \"courseId\",expires_at AS \"expiresAt\"",[order.member_id,course_id,order.id,start,order.duration_days])).rows[0])}
  }else updated=(await client.query("UPDATE member_accounts SET membership_expires_at=GREATEST(COALESCE(membership_expires_at,$2),$2)+($3||' days')::interval,updated_at=now() WHERE id=$1 RETURNING membership_expires_at",[order.member_id,paidAt,order.duration_days])).rows[0];
  await client.query("UPDATE member_orders SET status='paid',provider_transaction_id=$2,payment_type=$3,paid_at=$4,fulfilled_at=now(),updated_at=now() WHERE id=$1",[order.id,transactionId,paymentType,paidAt]);
  try{await client.query("INSERT INTO member_access_ledger(member_id,source_type,source_id,days_delta,previous_expires_at,resulting_expires_at,actor) VALUES($1,'payment',$2,$3,$4,$5,'provider') ON CONFLICT DO NOTHING",[order.member_id,order.order_id,order.duration_days,account?.membership_expires_at||null,updated?.membership_expires_at||account?.membership_expires_at||null])}catch(e){if(e.code!=='42P01')throw e}
  return order.access_mode==='selected'?{applied:true,accessMode:'selected',courseGrants}:{applied:true,accessMode:'legacy_all',expiresAt:updated.membership_expires_at};
});
