import { FormEvent,useEffect,useState } from 'react';
import { Link,useNavigate,useParams } from 'react-router-dom';
import { fetchPublicContentItem,ContentItem } from '@/lib/cms';
import { Input } from '@/components/ui/input';import { Button } from '@/components/ui/button';import { Label } from '@/components/ui/label';import SimpleContent from '@/components/SimpleContent';import useMidtransSnap from '@/hooks/use-midtrans-snap';import { toast } from 'sonner';
export default function CompetitionDetail(){
  useMidtransSnap();const navigate=useNavigate();const {slug=''}=useParams();const [item,setItem]=useState<ContentItem>();const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [proof,setProof]=useState('');const [error,setError]=useState('');
  useEffect(()=>{fetchPublicContentItem('competition',slug).then(setItem).catch(()=>setError('Lomba tidak ditemukan'))},[slug]);
  async function waitPaid(accessToken:string){const base=import.meta.env.VITE_API_URL||'';for(let i=0;i<60;i++){const r=await fetch(`${base}/api/competition-registration/${accessToken}`,{cache:'no-store'});if(r.ok){const d=await r.json();if(d.registration.paymentStatus==='paid')return navigate(`/lomba/${slug}/konfirmasi/${accessToken}`)}await new Promise(resolve=>setTimeout(resolve,2000))}toast('Pembayaran sedang diverifikasi. Simpan halaman ini dan buka kembali beberapa saat lagi.');navigate(`/lomba/${slug}/konfirmasi/${accessToken}`)}
  async function upload(file:File){setUploading(true);setError('');try{const base=import.meta.env.VITE_API_URL||'';const body=new FormData();body.append('file',file);const r=await fetch(`${base}/api/competitions/${slug}/book-proof`,{method:'POST',body});const d=await r.json();if(!r.ok)throw new Error(d.message);setProof(d.url)}catch(x){setError(x instanceof Error?x.message:'Upload gagal')}finally{setUploading(false)}}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const body=Object.fromEntries(form);try{const base=import.meta.env.VITE_API_URL||'';const r=await fetch(`${base}/api/competitions/${slug}/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,bookProofUrl:proof,consent:form.get('consent')==='on'})});const d=await r.json();if(!r.ok)throw new Error(d.message);if(d.free)return navigate(`/lomba/${slug}/konfirmasi/${d.accessToken}`);if(d.token&&window.snap){window.snap.pay(d.token,{onSuccess:()=>void waitPaid(d.accessToken),onPending:()=>void waitPaid(d.accessToken),onError:()=>{setBusy(false);toast.error('Pembayaran gagal. Silakan coba lagi.')},onClose:()=>{setBusy(false);toast('Pembayaran belum selesai.')}})}else location.href=d.paymentUrl}catch(x){setError(x instanceof Error?x.message:'Gagal mendaftar');setBusy(false)}}
  if(!item)return <main className="p-8">{error||'Memuat…'}</main>;const requirement=String(item.metadata.bookRequirement||'none');const buyUrl=String(item.metadata.bookPurchaseUrl||'/#buku-best-seller');
  return <main className="min-h-screen bg-[#fff8ef] p-5"><div className="mx-auto max-w-4xl space-y-6"><Link to="/lomba">← Semua lomba</Link>{item.imageUrl&&<img src={item.imageUrl} alt={item.title} className="max-h-[520px] w-full rounded-3xl object-cover"/>}<h1 className="text-4xl font-black">{item.title}</h1><div className="grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-3"><b>{String(item.metadata.eventDate||'Tanggal menyusul')}</b><b>{String(item.metadata.location||'Lokasi menyusul')}</b><b>Rp {Number(item.price).toLocaleString('id-ID')}</b></div><SimpleContent content={item.description}/><form onSubmit={submit} className="grid gap-4 rounded-3xl border-2 bg-white p-6 sm:grid-cols-2"><h2 className="text-2xl font-black sm:col-span-2">{Number(item.price)===0?'Daftar gratis':'Daftar dan bayar QRIS'}</h2>{[['participantName','Nama peserta','text'],['birthDate','Tanggal lahir','date'],['schoolName','Asal sekolah (opsional)','text'],['parentName','Nama orang tua/wali','text'],['whatsapp','Nomor WhatsApp','tel'],['email','Email','email']].map(([n,l,t])=><div key={n}><Label htmlFor={n}>{l}</Label><Input id={n} name={n} type={t} required={n!=='schoolName'}/></div>)}{Number(item.price)===0&&<div className="space-y-3 rounded-2xl border border-amber-300 bg-amber-50 p-4 sm:col-span-2"><div><b>Pendaftaran gratis untuk pemilik buku Nala</b><p className="mt-1 text-sm text-muted-foreground">Masukkan ISBN yang tercetak di sampul belakang buku Nala. Belum punya bukunya? Beli melalui tombol di bawah.</p></div><div><Label htmlFor="isbn">ISBN buku Nala</Label><Input id="isbn" name="isbn" required inputMode="numeric" placeholder="Masukkan ISBN buku"/></div><Button type="button" variant="outline" asChild><a href={buyUrl} target="_blank" rel="noreferrer">Belum punya buku? Beli buku di sini</a></Button></div>}{requirement!=='none'&&<div className="space-y-3 rounded-2xl border p-4 sm:col-span-2"><b>{requirement==='required'?'Wajib punya buku Nala':'Punya buku Nala? Unggah bukti jika ada'}</b><p className="text-sm">Unggah foto anak bersama buku. Bukti hanya dapat dilihat admin.</p><Input type="file" accept="image/jpeg,image/png,image/webp,image/gif" required={requirement==='required'&&!proof} disabled={uploading} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/>{proof&&<p className="text-sm text-emerald-700">Foto berhasil diunggah.</p>}<Button type="button" variant="outline" asChild><a href={buyUrl} target="_blank" rel="noreferrer">Belum punya buku? Beli buku dengan klik di sini</a></Button></div>}<label className="flex gap-2 sm:col-span-2"><input name="consent" type="checkbox" required/>Saya menyetujui syarat lomba dan dokumentasi peserta.</label>{error&&<p role="alert" className="text-destructive sm:col-span-2">{error}</p>}<Button disabled={busy||uploading} className="sm:col-span-2">{busy?'Menunggu pembayaran…':uploading?'Mengunggah foto…':'Daftar Gratis'}</Button></form></div></main>}
