import { FormEvent, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';

type Worksheet={id:number;title:string;originalName:string;byteSize:number};
type Lesson={id:number;title:string;description:string;youtubeVideoId:string|null;sortOrder:number;isPreview:boolean;worksheets:Worksheet[]};
type Chapter={id:number;title:string;sortOrder:number;lessons:Lesson[]};
type Course={id:number;title:string;slug:string;description:string;category:string;image_url:string|null;status:'draft'|'published'|'archived';sort_order:number;chapters:Chapter[]};
const base=`${import.meta.env.VITE_API_URL||''}/api/admin/member`;
async function call(path:string,init:RequestInit={}){const headers=init.body instanceof FormData?undefined:{'Content-Type':'application/json'};const r=await fetch(base+path,{credentials:'include',headers,...init});const x=await r.json().catch(()=>({message:'Respons server tidak valid'}));if(!r.ok)throw Error(x.message||'Permintaan gagal');return x}
const payload=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form));
export default function MemberCoursesAdmin(){
 const [courses,setCourses]=useState<Course[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState<number|null>(null);
 const load=async()=>{try{setError('');setCourses((await call('/courses')).courses)}catch(e){setError((e as Error).message)}};
 useEffect(()=>{load()},[]);
 const run=async(fn:()=>Promise<unknown>)=>{try{setBusy(true);setError('');await fn();await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const createCourse=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget,x=payload(f);run(async()=>{await call('/courses',{method:'POST',body:JSON.stringify({...x,sortOrder:Number(x.sortOrder),status:'draft'})});f.reset()})};
 const saveCourse=(e:FormEvent<HTMLFormElement>,id:number)=>{e.preventDefault();const x=payload(e.currentTarget);run(()=>call(`/courses/${id}`,{method:'PUT',body:JSON.stringify({...x,sortOrder:Number(x.sortOrder)})}))};
 const createChild=(e:FormEvent<HTMLFormElement>,kind:'chapters'|'lessons',parent:{courseId?:number;chapterId?:number})=>{e.preventDefault();const f=e.currentTarget,x=payload(f);run(async()=>{await call('/'+kind,{method:'POST',body:JSON.stringify({...parent,...x,sortOrder:Number(x.sortOrder),isPreview:x.isPreview==='on'})});f.reset()})};
 const saveChild=(e:FormEvent<HTMLFormElement>,kind:'chapters'|'lessons',id:number)=>{e.preventDefault();const x=payload(e.currentTarget);run(()=>call(`/${kind}/${id}`,{method:'PUT',body:JSON.stringify({...x,sortOrder:Number(x.sortOrder),isPreview:x.isPreview==='on'})}))};
 const remove=(kind:string,id:number,label:string)=>{if(confirm(`Hapus ${label}? Tindakan ini tidak dapat dibatalkan.`))run(()=>call(`/${kind}/${id}`,{method:'DELETE'}))};
 const upload=async(lessonId:number,file?:File)=>{if(!file)return;if(file.type!=='application/pdf'||file.size>10*1024*1024){setError('Pilih PDF maksimal 10MB.');return}const base64=await new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(file)});run(()=>call('/worksheets',{method:'POST',body:JSON.stringify({lessonId,title:file.name.replace(/\.pdf$/i,''),fileName:file.name,base64})}))};
 const download=async(w:Worksheet)=>{try{const r=await fetch(`${base}/worksheets/${w.id}`,{credentials:'include'});if(!r.ok)throw Error('Worksheet gagal diunduh');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=w.originalName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError((e as Error).message)}};
 return <section className="space-y-5">
  <header><h2 className="text-2xl font-bold">Kursus Member</h2><p className="text-muted-foreground">Kelola struktur kelas, materi, status publikasi, dan worksheet.</p></header>
  {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}
  <form onSubmit={createCourse} className="grid gap-3 rounded-2xl border bg-card p-4 md:grid-cols-2">
   <h3 className="col-span-full text-lg font-bold">Kursus baru</h3><Input name="title" required maxLength={200} placeholder="Judul kursus"/><Input name="slug" required pattern="[a-z0-9-]{2,100}" placeholder="slug-kursus"/><Textarea name="description" maxLength={5000} placeholder="Deskripsi"/><div className="grid gap-3"><Input name="category" maxLength={100} placeholder="Kategori"/><Input name="imageUrl" type="url" placeholder="URL thumbnail (HTTPS)"/><Input name="sortOrder" type="number" defaultValue="0" aria-label="Urutan"/></div><Button disabled={busy}>Tambah draft</Button>
  </form>
  <div className="space-y-4">{courses.map(c=><article key={c.id} className="rounded-2xl border bg-card p-4">
   <div className="flex flex-wrap items-center justify-between gap-2"><div><b className="text-lg">{c.title}</b><span className="ml-2 rounded-full bg-muted px-2 py-1 text-xs font-bold uppercase">{c.status}</span></div><Button variant="outline" onClick={()=>setOpen(open===c.id?null:c.id)}>{open===c.id?'Tutup':'Kelola'}</Button></div>
   {open===c.id&&<div className="mt-4 space-y-4">
    <form onSubmit={e=>saveCourse(e,c.id)} className="grid gap-3 rounded-xl bg-muted/40 p-3 md:grid-cols-2"><Input name="title" defaultValue={c.title} required/><Input name="slug" defaultValue={c.slug} required pattern="[a-z0-9-]{2,100}"/><Textarea name="description" defaultValue={c.description}/><div className="grid gap-3"><Input name="category" defaultValue={c.category}/><Input name="imageUrl" type="url" defaultValue={c.image_url||''} placeholder="URL thumbnail"/><Input name="sortOrder" type="number" defaultValue={c.sort_order}/><select name="status" defaultValue={c.status} className="h-10 rounded-md border bg-background px-3" aria-label="Status publikasi"><option value="draft">Draft / preview admin</option><option value="published">Publikasikan</option><option value="archived">Arsipkan</option></select></div><div className="flex flex-wrap gap-2"><Button disabled={busy}>Simpan kursus</Button><Button type="button" variant="destructive" onClick={()=>remove('courses',c.id,`kursus ${c.title}`)}>Arsipkan</Button></div></form>
    <form onSubmit={e=>createChild(e,'chapters',{courseId:c.id})} className="flex flex-wrap gap-2 rounded-xl border p-3"><Input className="min-w-52 flex-1" name="title" required placeholder="Judul bab baru"/><Input className="w-28" name="sortOrder" type="number" defaultValue="0" aria-label="Urutan bab"/><Button disabled={busy}>Tambah bab</Button></form>
    {(c.chapters||[]).map(ch=><section key={ch.id} className="ml-0 rounded-xl border-l-4 border-primary bg-background p-3 md:ml-4">
     <form onSubmit={e=>saveChild(e,'chapters',ch.id)} className="flex flex-wrap gap-2"><Input className="min-w-48 flex-1" name="title" defaultValue={ch.title} required/><Input className="w-24" name="sortOrder" type="number" defaultValue={ch.sortOrder} aria-label="Urutan bab"/><Button size="sm" disabled={busy}>Simpan bab</Button><Button type="button" size="sm" variant="destructive" onClick={()=>remove('chapters',ch.id,`bab ${ch.title}`)}>Hapus</Button></form>
     <div className="mt-3 space-y-3">{(ch.lessons||[]).map(l=><form key={l.id} onSubmit={e=>saveChild(e,'lessons',l.id)} className="grid gap-2 rounded-xl bg-muted/50 p-3 md:grid-cols-2"><Input name="title" defaultValue={l.title} required/><Input name="youtubeVideoId" defaultValue={l.youtubeVideoId||''} pattern="[A-Za-z0-9_-]{11}" placeholder="YouTube video ID (11 karakter)"/><Textarea name="description" defaultValue={l.description} placeholder="Deskripsi materi"/><div className="space-y-2"><Input name="sortOrder" type="number" defaultValue={l.sortOrder}/><label className="flex items-center gap-2"><input name="isPreview" type="checkbox" defaultChecked={l.isPreview}/> Pratinjau tanpa akses aktif</label><div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy}>Simpan materi</Button><Button type="button" size="sm" variant="destructive" onClick={()=>remove('lessons',l.id,`materi ${l.title}`)}>Hapus</Button></div></div><div className="col-span-full rounded-lg border bg-background p-3"><b>Worksheet PDF</b><Input className="mt-2" type="file" accept="application/pdf,.pdf" aria-label={`Unggah worksheet untuk ${l.title}`} onChange={e=>{upload(l.id,e.target.files?.[0]);e.target.value=''}}/>{(l.worksheets||[]).map(w=><div key={w.id} className="mt-2 flex flex-wrap items-center justify-between gap-2"><span>{w.title} <small>({Math.ceil(w.byteSize/1024)} KB)</small></span><span className="flex gap-2"><Button type="button" size="sm" variant="outline" onClick={()=>download(w)}>Unduh</Button><Button type="button" size="sm" variant="destructive" onClick={()=>remove('worksheets',w.id,`worksheet ${w.title}`)}>Hapus</Button></span></div>)}</div></form>)}
      <form onSubmit={e=>createChild(e,'lessons',{chapterId:ch.id})} className="grid gap-2 rounded-xl border border-dashed p-3 md:grid-cols-2"><Input name="title" required placeholder="Judul materi baru"/><Input name="youtubeVideoId" pattern="[A-Za-z0-9_-]{11}" placeholder="YouTube video ID"/><Textarea name="description" placeholder="Deskripsi"/><div className="grid gap-2"><Input name="sortOrder" type="number" defaultValue="0"/><label className="flex items-center gap-2"><input name="isPreview" type="checkbox"/> Jadikan pratinjau</label><Button disabled={busy}>Tambah materi</Button></div></form>
     </div></section>)}
   </div>}
  </article>)}</div>
 </section>
}
