import {FormEvent,useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';import {Input} from '@/components/ui/input';import {Label} from '@/components/ui/label';import {Textarea} from '@/components/ui/textarea';
const base=`${import.meta.env.VITE_API_URL||''}/api/admin/member-program`;
async function api(path:string,init:RequestInit={}){const r=await fetch(base+path,{credentials:'include',headers:{'Content-Type':'application/json'},...init}),x=await r.json().catch(()=>({message:'Respons server tidak valid'}));if(!r.ok)throw Error(x.message||'Permintaan gagal');return x}
const local=(v?:string|null)=>v?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)).replace(' ','T'):'';
const utc=(v:string)=>v?new Date(`${v}:00+07:00`).toISOString():null;
const Box=({title,children}:{title:string,children:any})=><Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-3">{children}</CardContent></Card>;
export default function MemberProgramAdmin(){const [tab,setTab]=useState('settings'),[data,setData]=useState<any>({flags:[],plans:[],vouchers:[]}),[questions,setQuestions]=useState<any[]>([]),[artworks,setArtworks]=useState<any[]>([]),[challenges,setChallenges]=useState<any[]>([]),[certificates,setCertificates]=useState<any[]>([]),[courses,setCourses]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[code,setCode]=useState('');
 const load=async()=>{try{const [c,q,a,h,z,k]=await Promise.all([api('/config'),api('/questions'),api('/artworks'),api('/challenges'),api('/certificates'),fetch(`${import.meta.env.VITE_API_URL||''}/api/admin/member/courses`,{credentials:'include'}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.message);return x})]);setData(c);setQuestions(q.questions);setArtworks(a.artworks);setChallenges(h.challenges);setCertificates(z.certificates);setCourses(k.courses)}catch(e){setMessage((e as Error).message)}};
 useEffect(()=>{load()},[]);const act=async(fn:()=>Promise<any>,ok='Tersimpan')=>{if(busy)return;setBusy(true);setMessage('');try{const x=await fn();setMessage(ok);await load();return x}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
 const submit=(path:string,map:(f:FormData)=>any,ok?:string)=>(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),form=e.currentTarget;act(()=>api(path,{method:'POST',body:JSON.stringify(map(f))}),ok).then(x=>{if(x){if(x.code)setCode(x.code);form.reset()}})};
 const tabs=[['settings','Pengaturan & paket'],['release','Jadwal rilis'],['qa','Tanya jawab'],['art','Karya & galeri'],['challenge','Tantangan'],['cert','Sertifikat']];
 return <div className="space-y-4"><div><h2 className="text-3xl font-black">Program Member</h2><p className="text-sm text-muted-foreground">Kontrol pemilik. Fitur baru aman dalam keadaan nonaktif sampai dinyalakan.</p></div><div className="flex flex-wrap gap-2" role="tablist">{tabs.map(([v,l])=><Button key={v} variant={tab===v?'default':'outline'} onClick={()=>setTab(v)}>{l}</Button>)}</div>{message&&<p role="status" className="rounded-xl border bg-white p-3">{message}</p>}<fieldset disabled={busy} className="grid gap-4 lg:grid-cols-2">
 {tab==='settings'&&<><Box title="Feature flags">{data.flags.map((x:any)=><label key={x.key} className="flex items-center justify-between rounded-lg border p-3"><span>{x.key}</span><input type="checkbox" checked={x.enabled} onChange={e=>act(()=>api(`/flags/${x.key}`,{method:'PUT',body:JSON.stringify({enabled:e.target.checked})}))}/></label>)}</Box><Box title="Paket akses"><form className="grid gap-2" onSubmit={submit('/plans',f=>({name:f.get('name'),durationDays:Number(f.get('days')),price:Number(f.get('price'))}))}><Label>Nama paket</Label><Input name="name" required maxLength={100}/><Label>Durasi hari</Label><Input name="days" type="number" min="1" max="730" required/><Label>Harga rupiah</Label><Input name="price" type="number" min="1" required/><Button>Tambah paket</Button></form>{data.plans.map((p:any)=><form key={p.id} className="grid grid-cols-2 gap-2 rounded-lg border p-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(()=>api(`/plans/${p.id}`,{method:'PUT',body:JSON.stringify({name:f.get('name'),durationDays:Number(f.get('days')),price:Number(f.get('price')),status:f.get('status')})}))}}><Input name="name" defaultValue={p.name}/><Input name="days" type="number" defaultValue={p.duration_days}/><Input name="price" type="number" defaultValue={p.price}/><select name="status" defaultValue={p.status} className="rounded-md border p-2"><option value="active">active</option><option value="archived">archived</option></select><Button className="col-span-2">Simpan</Button></form>)}</Box><Box title="Voucher akses"><form className="grid gap-2" onSubmit={submit('/vouchers',f=>({label:f.get('label'),reason:f.get('reason'),days:Number(f.get('days')),maxUses:Number(f.get('max')),expiresAt:utc(String(f.get('expires')))}),'Voucher dibuat. Salin kode sekarang; kode tidak dapat dilihat lagi.')}><Input name="label" placeholder="Label" required/><Textarea name="reason" placeholder="Alasan" required/><div className="grid grid-cols-3 gap-2"><Input name="days" type="number" min="1" placeholder="Hari" required/><Input name="max" type="number" min="1" placeholder="Maks pakai" required/><Input name="expires" type="datetime-local" required/></div><Button>Buat voucher</Button></form>{code&&<div className="rounded-lg bg-amber-100 p-3"><b>Kode sekali tampil:</b><code className="block break-all">{code}</code></div>}{data.vouchers.map((v:any)=><div key={v.id} className="flex justify-between rounded-lg border p-2"><span>{v.label} · {v.uses}/{v.max_uses}</span>{!v.archived_at&&<Button variant="destructive" onClick={()=>confirm('Arsipkan voucher ini?')&&act(()=>api(`/vouchers/${v.id}`,{method:'DELETE'}))}>Arsipkan</Button>}</div>)}</Box></>}
 {tab==='release'&&<Box title="Jadwal rilis (WIB)">{courses.map((c:any)=><div key={c.id} className="space-y-2 rounded-xl border p-3"><b>{c.title}</b><Release kind="course" id={c.id} value={c.release_at} act={act}/>{c.chapters?.flatMap((h:any)=>h.lessons||[]).map((l:any)=><div key={l.id} className="ml-3 border-l pl-3"><span>{l.title}</span><Release kind="lesson" id={l.id} value={l.releaseAt||l.release_at} act={act}/></div>)}</div>)}</Box>}
 {tab==='qa'&&<Box title="Antrean pertanyaan">{questions.map(q=><form key={q.id} className="space-y-2 rounded-xl border p-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(()=>api(`/questions/${q.id}`,{method:'PUT',body:JSON.stringify({status:f.get('status'),answer:f.get('status')==='closed'?null:f.get('answer')})}))}}><b>{q.course_title}</b><p>{q.question}</p><Textarea name="answer" defaultValue={q.answer||''} placeholder="Jawaban privat"/><select name="status" defaultValue={q.status==='answered'?'answered':'closed'} className="rounded-md border p-2"><option value="answered">Jawab</option><option value="closed">Tutup</option></select><Button>Simpan</Button></form>)}</Box>}
 {tab==='art'&&<Box title="Karya privat & galeri">{artworks.map(a=><div key={a.id} className="space-y-2 rounded-xl border p-3"><img src={`${base}/artworks/${a.id}/image`} alt={`Karya ${a.title}`} className="max-h-64 rounded object-contain"/><b>{a.title}</b><p>Status galeri: {a.gallery_status||'belum diajukan'}</p><form onSubmit={e=>{e.preventDefault();act(()=>api(`/artworks/${a.id}/feedback`,{method:'PUT',body:JSON.stringify({feedback:new FormData(e.currentTarget).get('feedback')})}))}}><Textarea name="feedback" defaultValue={a.feedback||''} required/><Button className="mt-2">Simpan feedback</Button></form>{a.gallery_status==='pending'&&<div className="flex gap-2"><Button onClick={()=>act(()=>api(`/gallery/${a.id}`,{method:'PUT',body:JSON.stringify({status:'approved'})}))}>Setujui galeri</Button><Button variant="outline" onClick={()=>act(()=>api(`/gallery/${a.id}`,{method:'PUT',body:JSON.stringify({status:'rejected'})}))}>Tolak</Button></div>}<Button variant="destructive" onClick={()=>confirm('Hapus karya privat permanen?')&&act(()=>api(`/artworks/${a.id}`,{method:'DELETE'}))}>Hapus karya</Button></div>)}</Box>}
 {tab==='challenge'&&<Box title="Tantangan"><ChallengeForm submit={submit('/challenges',challengeBody)}/>{challenges.map(c=><ChallengeForm key={c.id} value={c} submit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(()=>api(`/challenges/${c.id}`,{method:'PUT',body:JSON.stringify(challengeBody(f))}))}}/>)}</Box>}
 {tab==='cert'&&<><Box title="Aturan sertifikat">{courses.map((c:any)=><div key={c.id} className="flex items-center justify-between rounded-lg border p-3"><span>{c.title}</span><div className="flex gap-2"><Button onClick={()=>act(()=>api(`/certificates/${c.id}`,{method:'PUT',body:JSON.stringify({enabled:true})}))}>Aktifkan</Button><Button variant="outline" onClick={()=>act(()=>api(`/certificates/${c.id}`,{method:'PUT',body:JSON.stringify({enabled:false})}))}>Nonaktifkan</Button></div></div>)}</Box><Box title="Sertifikat terbit">{certificates.length===0&&<p className="text-sm text-muted-foreground">Belum ada sertifikat terbit.</p>}{certificates.map((c:any)=><div key={c.certificateId} className="rounded-lg border p-3"><b>{c.displayName}</b><p>{c.courseTitle} · {c.memberEmail}</p><p className="text-xs text-muted-foreground">{c.certificateId}</p>{c.revokedAt?<p>Dicabut {local(c.revokedAt)}</p>:<Button variant="destructive" onClick={()=>confirm('Cabut sertifikat terbit ini? Tindakan tercatat dan tidak dapat dibatalkan dari layar ini.')&&act(()=>api(`/certificates/${c.certificateId}`,{method:'DELETE'}),'Sertifikat dicabut')}>Cabut sertifikat</Button>}</div>)}</Box></>}
 </fieldset></div>}
function Release({kind,id,value,act}:any){const [v,setV]=useState(local(value));return <div className="flex gap-2"><Input type="datetime-local" value={v} onChange={e=>setV(e.target.value)}/><Button type="button" onClick={()=>act(()=>api(`/release/${kind}/${id}`,{method:'PUT',body:JSON.stringify({releaseAt:utc(v)})}))}>Simpan WIB</Button><Button type="button" variant="outline" onClick={()=>{setV('');act(()=>api(`/release/${kind}/${id}`,{method:'PUT',body:JSON.stringify({releaseAt:null})}))}}>Langsung</Button></div>}
const challengeBody=(f:FormData)=>({title:f.get('title'),prompt:f.get('prompt'),opensAt:utc(String(f.get('opens'))),closesAt:utc(String(f.get('closes'))),status:f.get('status')});
function ChallengeForm({submit,value}:any){return <form className="grid gap-2 rounded-xl border p-3" onSubmit={submit}><Input name="title" defaultValue={value?.title} placeholder="Judul" required/><Textarea name="prompt" defaultValue={value?.prompt} placeholder="Instruksi" required/><div className="grid grid-cols-2 gap-2"><label>Buka WIB<Input name="opens" type="datetime-local" defaultValue={local(value?.opens_at)} required/></label><label>Tutup WIB<Input name="closes" type="datetime-local" defaultValue={local(value?.closes_at)} required/></label></div><select name="status" defaultValue={value?.status||'draft'} className="rounded-md border p-2"><option value="draft">draft</option><option value="published">published</option><option value="archived">archived</option></select><Button>{value?'Simpan tantangan':'Tambah tantangan'}</Button></form>}
